### PR TITLE
GitHub Pages version for easier navigation inside this repository

### PR DESCRIPTION
**Pull request by nilsweb**
Hey Everyone,

since I hadn't much to do over the holidays, I decided to take on #128 and create a GitHub Pages version of this repository so that people can find the code corresponding to each video more easily.

**Included features**:
- Overview of all videos (tutorials, streams, courses/sessions and coding challenges)
- Links to related videos, discussed topics, etc. (similar to what is currently present in the YouTube description of each video)
- Download-Link to the video's project
- Link to a running live example in the browser (currently only for p5.js sketches)
- Possibility to add upcoming streams with their topics which will be displayed on the website as well
- List of versions made by the community corresponding to each video 

You can have a look at the current state [here](https://nilsweb.github.io/Rainbow-Code/)!

As for now, not every video has been included as I am currently in the process of integrating everything.

If someone wants to help with this, you can check out my fork [here](https://github.com/nilsweb/Rainbow-Code/tree/gh-pages). There is also a rudimentary documentation on [how to add new videos](https://github.com/nilsweb/Rainbow-Code/wiki/Content-Contribution-Guide).

Therefore, I don't recommend merging my changes until the majority of videos are included.

If you have any further questions, feel free to contact me at any time!

### CODE REVIEW

**Comment by meiamsome** [comment]
This is amazing!

Lots of stuff to review, but what I've seen looks good to me. I'm not sure how user friendly adding contributions to that format is, but the current readme with no standards is probably worse. Should we add documentation into the format somehow or perhaps add a link explaining how to do it?

**Comment by nilsweb** [comment]
Thanks!

During development I tried to keep everything as simple as possible for the end-user.
If you take a look at e.g. [this video](https://nilsweb.github.io/Rainbow-Code/CodingChallenges/82-kittenizer-chrome-extension.html), you can find a link below the "Community Contribution" section taking you directly to the corresponding file opened in GitHub's editor. There is also some basic documentation on [how to add contributions](https://github.com/nilsweb/Rainbow-Code/wiki/Community-Contributions-Guide) which maybe needs some work (hard to say as the person who created it). I will add a link to this page as well.

**Comment by shiffman** [comment]
This is so incredible, I'm super excited about it! I'm just returning from holiday travels so hope to have more time to look this over today / tomorrow. In theory I would love for this to take over http://thecodingtrain.com (also http://codingtra.in). @nilsweb thank you, thank you! Happy new year! More soon.

**Comment by shiffman** [comment]
@nilsweb I'd love to discuss how to develop this out more! What's the best way to contact you off github (we can move back here after discussing how to proceed?).

**Comment by nilsweb** [comment]
Great to hear that you like it!

That‘s probably a good idea. Whatever works best for you (Skype, Discord, Mail, etc.). I‘m open for suggestions.

**Comment by shiffman** [comment]
Send me a note at daniel at shiffman dot net!

**Comment by shiffman** [comment]
🎉 🎉 🎉 🎉 🚂 🌈 🎉 🎉 🎉 🎉

**Pull request merged**
