### PR TITLE
Snake challenge update

### PR DESCRIPTION
**Pull request by a3zzat**
updating and adding some new features

### CODE REVIEW

**Comment by shiffman** [comment]
This is really terrific!  I prefer to keep the code here simple and have it match the video exactly. I do love all these additional features, though, perhaps you could make your own repo with them and I could link to it somehow?

**Comment by shiffman** [comment]
My new idea is to put READMEs in the challenge folders then people could link out to their improved code. Would you like to pull request that?

**Comment by SacrificeProductions** [comment]
Thats a great idea dan.

**Comment by strikemike2k** [comment]
I also was inspired by your video and decided to create a version of it myself. This was my first time using p5.js. The major differences I decided to include: 
- Queue the controls into an array to prevent more than one turn being activated per frame causing only the last control to run
- Added simple scoring and highscore
- Multiple food options at the same time

You can view the code repo here:
https://github.com/strikemike2k/snake
# Play it
And you can play it via GitHub pages here: 
https://strikemike2k.github.io/snake/

**Comment by strikemike2k** [comment]
I just added a README to the Snake game p5.js directory in PR #116

**Comment by shiffman** [comment]
I'm closing this in favor of #116, thank you for the contribution!!

**Pull request closed without merging**
