### PR TITLE
Create 46-asteroids.md

### PR DESCRIPTION
**Pull request by davenewt**
Hope this is right?! :)

### CODE REVIEW

**Comment by shiffman** [comment]
It looks good to me but I'll let @nilsweb check it before merging! Also, it should include fields for the code as well as maybe related links in addition to contributions?

**Comment by davenewt** [comment]
Thanks! I copied the first example from https://github.com/nilsweb/Rainbow-Code/wiki/Community-Contributions-Guide which doesn't include those fields? Maybe they could be added to the example in that case. I also missed the description from the video, which is below if @nilsweb wants to copy/paste it in:

This video is Part 1 of a new Coding Challenge: the classic Atari video game Asteroids!  In this video, I use JavaScript and HTML5 canvas with the p5.js library to program the ship and the asteroids.

**Comment by nilsweb** [comment]
I updated some properties to reflect the recent changes made in the API. Sorry @davenewt that I forgot to update the documentation.

Regarding your comment about the missing fields: I also forgot to add a link to the [Content Contribution Guide](https://github.com/nilsweb/Rainbow-Code/wiki/Content-Contribution-Guide) in case nobody has added a definition file yet.

**Comment by shiffman** [comment]
Yay, great work everyone!

**Pull request merged**
