### PR TITLE
Added my version of the clock

### PR DESCRIPTION
**Pull request by ignazioc**

### CODE REVIEW

**Comment by addyh** [comment]
That's cool! Have you thought about making the colon blink at the same time as the second changes?

**Comment by ignazioc** [comment]
was like this at the beginning, but it was a bit "slow", so now blinks faster. But I also agree with you that's a bit annoying. Let's rename this clock "OCD torture clock" :D

**Comment by ignazioc** [comment]
This is the other version https://alpha.editor.p5js.org/ignazioc/sketches/B1bPjAfef

**Comment by meiamsome** [comment]
Hey, this is great! Just thought I'd point out that the 60 never lights

**Pull request merged**
