### PR TITLE
Auto-detection for p5.js and Processing code

### PR DESCRIPTION
**Pull request by nilsweb**
In reference to #359

From the first commit:
- If multiple code variations are found for one repository, they will be
  displayed as a dropdown when downloading the code.
- If one of the found code variations is suitable as a live example, it
  will also be used as that.
- If there is only one variation for the given repository, it will be used
  when downloading the code.
- If no variation is found, the repository will be used "as is" (without
  adding a suffix) for downloading and as the live_example.
- If you link to an external repository, it will be used for downloading
  but not as the live example.
- Specifiying live_example will override any automatically set live example.
- `live_example: false` will disable the live example button.
- Setting `repository: false` will display a message saying that the code
  hasn't been added yet (but will be added in the future).
- Setting `repository: null` (or omitting it) will hide any code actions.The following behaviour is to be expected:
- If multiple code variations are found for one repository, they will be
  displayed as a dropdown when downloading the code.
- If one of the found code variations is suitable as a live example, it
  will also be used as that.
- If there is only one variation for the given repository, it will be used
  when downloading the code.
- If no variation is found, the repository will be used "as is" (without
  adding a suffix) for downloading and as the live_example.
- If you link to an external repository, it will be used for downloading
  but not as the live example.
- Specifiying live_example will override any automatically set live example.
- `live_example: false` will disable the live example button.
- Setting `repository: false` will display a message saying that the code
  hasn't been added yet (but will be added in the future).
- Setting `repository: null` (or omitting it) will hide any code actions.

**The documentation also needs to be updated to reflect the new behaviour!**

### CODE REVIEW

**Comment by shiffman** [comment]
This all sounds great! I'm slightly worried it'll be complicated for contributors but let's give it a try and in the end I think it will actually be quite simple once we have a "template" for people to copy from.

Also, one thing to watch out for, if you rename a directory for a Processing sketch, i.e.

```
CC_Snake/ --> CC_Snake_Processing/
```

you have to rename the main PDE file also:

```
CC_Snake/CC_Snake.pde --> CC_Snake_Processing/CC_Snake_Processing.pde
```

otherwise the Processing IDE will fail to open the sketch properly.

**Comment by nilsweb** [comment]
I tried to make the `repository` field behave more "naturally".
I didn't know about the Processing naming convention, but knowing it now, wouldn't it be better to create separate folders inside `CodingChallenges` for each system? This means that all Processing versions go under `CodingChallenges/Processing` and p5.js versions go under `CodingChallenges/p5.js` (similar to whats currently going on inside the `Tutorials` folder). Otherwise every time a processing version is added, the folder and main file would have to be renamed accordingly. Also, I think it would be easier for future contributors now knowing about the suffixes `_Processing` and `_p5.js`. Folders would be more understandable.

**Comment by shiffman** [comment]
@nilsweb I agree, this sounds like a better plan. Would it be:

```
CodingChallenges/CodingChallenge_03_Snake/Processing/...
CodingChallenges/CodingChallenge_03_Snake/p5.js/...
```

or

```
CodingChallenges/Processing/CodingChallenge_03_Snake/...
CodingChallenges/p5.js/CodingChallenge_03_Snake/...
```

One the one hand I like the first best b/c most people are looking for a specific challenge? But this would actually then require another subfolder for Processing, i.e.

```
CodingChallenges/CodingChallenge_03_Snake/Processing/Snake/Snake.pde
CodingChallenges/CodingChallenge_03_Snake/p5.js/index.html
CodingChallenges/CodingChallenge_03_Snake/p5.js/sketch.js
```

**Comment by nilsweb** [comment]
@shiffman Right, haven't thought about the second subfolder... But at some point, people should use the website to download the code so I think it doesn't matter if we use option two?

**Comment by shiffman** [comment]
@nilsweb yes but for anyone working on adding and testing code to the site not having the folder name match the `pde` file will be a major pain. So that folder is necessary.

**Comment by nilsweb** [comment]
@shiffman I understand. That's why I'd go with this folder structure:

```
CodingChallenges/Processing/CodingChallenge_03_Snake/
    - CodingChallenge_03_Snake.pde
    - ...
CodingChallenges/Processing/CodingChallenge_03_Snake/
    - index.html
    - ...
```

Therefore, we don't have any "ugly" folders inside the actual CC folders (which I think would be more counter intuitive than having to decide on the code variation first) and Processing is happy having a main file matching the folder name.

**Comment by Merijn-DH** [comment]
I don't know if my opinion is of any value here, but having a folder structure of `CodingChallenges/Processing/` and 
`CodingChallenges/p5.js/` does not sound logical to me. 
People looking for a specific coding challenge will get confused over which folder it is in and it won't be clear they are available in both versions (of course this only happens when browsing the github and not the website, but I think the github should stay equally usable as the website).

Myself, I'm in favor of either using this stucture: 
```
CodingChallenges/CodingChallenge_03_Snake/Processing/Snake/Snake.pde
CodingChallenges/CodingChallenge_03_Snake/p5.js/index.html
CodingChallenges/CodingChallenge_03_Snake/p5.js/sketch.js
```

even though it requires an extra subfolder, or using the stucture that is used right now..

**Comment by shiffman** [comment]
I think I agree with @Merijn-DH here. @meiamsome is usually the voice of the reason, what say you?

**Comment by GreyWizard1955** [comment]
Guys (especially Daniel, Merijn and Nils),

We're getting to the point that we're already at 3 digits for LSs and close to 3 digits on CCs... Shouldn't we rename all of them to 3 digits before we get there??? JMHO…

Sent from Mail for Windows 10

**Comment by nilsweb** [comment]
Sorry @shiffman and @Merijn-DH but for some reason GitHub didn't notify me about the ongoing discussion...

@Merijn-DH You're right, that would be even more confusing and the GitHub repository should definitely stay useable (and logical/easy to navigate) as well.
I gave it a little more thought and came to the conclusion that the suggested structure would be best. As a reminder:

> ```
> CodingChallenges/CodingChallenge_03_Snake/Processing/Snake/Snake.pde
> CodingChallenges/CodingChallenge_03_Snake/p5.js/index.html
> CodingChallenges/CodingChallenge_03_Snake/p5.js/sketch.js
> ```

Therefore, the repository stays usable and the code people are looking for should be easy to find. Moreover, it's better for contributors when porting a coding challenge as well. If we would decide on the `_Processing` convention, people would also have to think about renaming their main Processing file so everything stays functional at that front. With the convention described by @Merijn-DH, this possible point of failure goes away.

BTW, the "ugly-folder-problem" I mentioned before is irrelevant since GitHub automatically "jumps" into a folder if there is only one subfolder. Haven't thought about that either...

If everyone agrees, I think it would be best to close/reject this PR and I'll open a new one referencing this conversation with the correct changes as it is easier for me to revert the commits and start from scratch anyway.

@blinkityblank Are you done with migrating all coding challenges? I'll wait with my second PR until you're done as we may get *a lot* of merge conflicts if those files change at the same time.

@GreyWizard1955 Could you please create a separate issue about this since it is a little off-topic and it may get lost otherwise?

**Comment by shiffman** [comment]
@nilsweb all sounds good to me!

**Comment by GreyWizard1955** [comment]
@nilsweb I posted in the Slack Channel as well… I just want it looked at… TYVM!!!

Sent from Mail for Windows 10

**Pull request closed without merging**
