### PR TITLE
Created CC90, filled remaining links and videos mentioned and created section for multi-part challenges

### PR DESCRIPTION
**Pull request by blinkityblank**
-Fixed the capitalization of the words "coding challenge" in the description
-Added the remaining links and videos mentioned in all the videos
-added a custom section called "Other parts in this challenge" to easily find other part in a multi-parts challenge
-Created .md file for Coding Challenge 90

If you guys can just take a quick look and approve if you think it's good to go.

Thanks!

### CODE REVIEW

**Comment by nilsweb** [comment]
@blinkityblank What do you think, should the “other parts” section become an official one since it may be used regularly?

**Comment by blinkityblank** [comment]
@nilsweb Yes I think it's a good idea. It's pretty common to have a multi-parts challenges.
I think I added it to like 30-40 videos already.

**Comment by shiffman** [comment]
This looks awesome, so excited to have all these up there!

**Comment by blinkityblank** [comment]
I believe the only thing missing from them is adding the community contributions.

**Comment by blinkityblank** [comment]
@nilsweb Great! I'll update my pull request.

**Comment by blinkityblank** [comment]
Alright, changed to the new notation of "parts:"
looks ready to merge but will let @nilsweb just take one last look.

**Comment by nilsweb** [comment]
Thanks @blinkityblank! Now all coding challenges should be migrated.

**Comment by shiffman** [comment]
Yay! What's the next step, should we delete the content from the deprecated README's and point to instructions for contributing?

**Comment by nilsweb** [comment]
@shiffman That would probably be a good idea.

**Comment by shiffman** [comment]
Ok, I'll open a new issue for that.

**Comment by blinkityblank** [comment]
The only thing missing from those is the community contribution(basically taking the old format from the READMEs and adding them to the new .md files.)

**Comment by shiffman** [comment]
Oh I didn't realize that, will update the issue, thank you!

**Pull request merged**
