### PR TITLE
CC_07_SolarSystemGenerator port to p5.js

### PR DESCRIPTION
**Pull request by madacoo**
p5.js version of CC_07_SolarSystemGenerator in response to issue #267

### CODE REVIEW

**Comment by meiamsome** [comment]
This is great!

I'll have a thorough check over in a couple hours and merge them in if all's ok!

Thanks!

**Comment by madacoo** [comment]
Hi, no problem! It was fun to do :)

I'm a bit new to GitHub so forgive me if I get anything wrong. Like I hadn't intended on the ForwardKinematic being part of the pull request since I hadn't finished checking it through yet. But it seems like it has been included anyway.

Let me know if there is anything that needs changing!

Cheers

**Comment by meiamsome** [comment]
@madacoo Yeah, that happens if you push more commits to the branch you used for the PR! Not to worry, they both look good to me.

**Comment by madacoo** [comment]
@meiamsome Now I know, aha!

Thanks!

**Pull request merged**
