### PR TITLE
add javascript version from langtonsant

### PR DESCRIPTION
**Pull request by vortami**

### CODE REVIEW

**Comment by vortami** [comment]
Whoops, accidently `pixelDensity(5);` is still in there on line 13.

**Comment by shiffman** [comment]
Thank you! Just curious did you try using `pixels` as well or just `point()`?

**Comment by vortami** [comment]
I tried it with pixels, but it didn't work. So I just used `point();`.

**Comment by vortami** [comment]
If I used the grid to draw it, it would run very slow.

**Pull request merged**
