### PR TITLE
Update sketch.js

### PR DESCRIPTION
**Pull request by lucky70707**
added code to start the snake as two blocks instead of one. Added code to check whether the generation point of a new food is in the same place as the tail of the snake.

### CODE REVIEW

**Comment by JosefKuchar** [comment]
You are not using proper formating, Dan will not merge it, i think

**Comment by prestoaghitato** [comment]
Also, the comments are in Dutch. Why? Very few people will understand.

**Comment by meiamsome** [comment]
Hey there, I see you closed this!

User edits aren't supposed to be added to this repository to keep them consistent with the videos. If you host your version somewhere, I'd be happy to link to it if you want

**Comment by lucky70707** [comment]
Nah the code is terrible anyway. When I originally made this I was just learning how to work with github and javascript. Thanks for the consideration though!

**Pull request closed without merging**
