### PR TITLE
sketch.js

### PR DESCRIPTION
**Pull request by mehedi238**
/*
6.4 p5.js The Constructor Function
Code for https://vimeo.com/channels/learningp5js/141211393
*/

var bubbles = [];

function setup() {
    createCanvas(600, 400);
    for (var i = 0; i < 4; i++) {
        bubbles[i] = new Bubble();
    }
}

function draw() {
    background(0);
    for (var i = 0; i < bubbles.length; i++) {
        bubbles[i].move();
        bubbles[i].display();
    }
}

class Bubble {
    Constructor() {
        this.x = random(0, width);
        this.y = random(0, height);
    }
    display() {
        stroke(255);
        noFill();
        ellipse(this.x, this.y, 24, 24);
    }

    move() {
        this.x = this.x + random(-1, 1);
        this.y = this.y + random(-1, 1);

    }
}

### CODE REVIEW

**Comment by meiamsome** [comment]
I am not sure this is what you intended to do, could you let me know what you meant?

**Comment by mehedi238** [comment]
/*
6.5 p5.js Adding Removing Objects
Code for https://vimeo.com/channels/learningp5js/141211392
Concepts introducing push(), splice() 1:30
*/

var bubbles = [];

function setup() {
    createCanvas(600, 400);
}

function mousePressed() {
    bubbles.push(new Bubble(mouseX, mouseY));
}

function draw() {
    background(0);
    for (var i = 0; i < bubbles.length; i++) {
        bubbles[i].move();
        bubbles[i].display();
    }
}

class Bubble {
    constructor() {
        this.x = x;
        this.y = y;
    }

    display() {
        stroke(255);
        fill(255, 0, 150, 50);
        ellipse(this.x, this.y, 24, 24);
    }

    move() {
        this.x = this.x + random(-1, 1);
        this.y = this.y + random(-1, 1);

    }
}

**Comment by mehedi238** [comment]
In tutorials there is  used es6 constructor function. In github there is
es5. I just want to updare this version.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by meiamsome** [comment]
Oh I see what you're saying sorry - I actually got around to uploading the latest versions of 6.x and 7.x recently (They've been renumbered now).

Sorry again...

**Comment by mehedi432** [comment]
In 7.6 Shiffman uses es5 and i want to update this with es6. I am a learner
& still learning from Shiffman. So, i thought that it is good to share with
what i just learned.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Pull request closed without merging**
