### PR TITLE
Added Coding Challenge 76 10PRINT Processing #267 and README of CC_12_LorenzAttractor #128 .

### PR DESCRIPTION
**Pull request by AryanGitHub**
Made Processing version of 10PRINT.
it is taking 0.5 as probability , not 0.9  as stated in Pull request #320

### CODE REVIEW

**Comment by shiffman** [comment]
Thanks for this! Did you mean to have the Lorenz attractor README In this pull request as well? Sorry to be slow about these.

**Comment by AryanGitHub** [comment]
Sorry ,finally I fixed a small problem in my Fork. Now putting pull request of  Coding Challenge 76 10PRINT Processing  and README of CC_12_LorenzAttractor.  Actually I am new on GIT-HUB . And thanks a lot 
 for your GITHUB for Poets Youtube Videos. It really helped me a lot , and made me to connected here.

**Comment by shiffman** [comment]
Thank you!

**Comment by AryanGitHub** [comment]
Thanks for accepting....

**Pull request merged**
