### PR TITLE
Create sketch-v2.js

### PR DESCRIPTION
**Pull request by SacrificeProductions**
Add variation to the original code without changing the master challenge code.

### CODE REVIEW

**Comment by shiffman** [comment]
This is great!  I think you can actually just put the edits directly in sketch.js, no need to keep the boxes.  Also, I think it's best if you pull request a version without your clever color variations.  Best to keep the example as simple as possible then others can create their own design variations.

**Comment by shiffman** [comment]
I think this is actually covered in #69!  Since this version has your own creative spin I think it's best for it to live in your own repo rather than in the examples?  Not sure the best way to handle this.

**Comment by SacrificeProductions** [comment]
Still learning github lol, will work something out. Whoops

**Comment by shiffman** [comment]
You're doing great!

**Pull request closed without merging**
